categories:
  - id: SLPM_861.83
    name: Main Executable
    paths:
      - SLPM_861.83

expected_paths:
  asm: expected/asm

ignored_files:
  - SLPM_861.83/header

output: ./objdiff.json
