name: pop'n music (JP)
sha1: baf9842c90a56bed42071753c92025c74900ebd7
options:
  basename: SLPM_861.83
  target_path: SLPM_861.83
  elf_path: build/SLPM_861.83.elf
  base_path: ..

  platform: psx
  compiler: GCC

  asm_path: asm/SLPM_861.83
  src_path: src/SLPM_861.83
  build_path: build

  ld_script_path: linker/SLPM_861.83.ld
  ld_dependencies: True

  create_undefined_funcs_auto: True
  create_undefined_syms_auto: True

  find_file_boundaries: False
  gp_value: 0x8007E9A4

  o_as_suffix: False
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/sym_data.txt
    - config/sym_functions.txt
  reloc_addrs_path:
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.SLPM_861.83.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.SLPM_861.83.txt

  extensions_path: tools/splat_ext

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  ld_align_section_vram_end: false
  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x56AF0
    subsegments:
      - [0x800, rodata]
      - [0x830, rodata]
      - [0x83C, rodata]
      - [0x848, rodata]
      - [0xB6C, rodata]
      - [0xFC0, rodata]
      - [0x191C, rodata]
      - [0x2130, rodata]
      - [0x23E4, rodata]
      - [0x3248, rodata]
      - [0x37AC, rodata]
      - [0x3858, rodata]
      - [0x39F4, rodata]
      - [0x45F8, rodata]
      - [0x479C, rodata]
      - [0x5F54, c, main]
      - [0x609C, c, fs]
      - [0x9328, asm]
      - [0x64F64, data]
      - [0x6F1A4, data, sdata]
  - [0x6F800]
